### ISSUE TITLE
Text Shadows and Stroke

### ISSUE THREAD

**Issue by Gauleiter** [gree/lwf#106]
I didn't find so far any way of doing text decoration for labels.
As far as I understand, Flash filters are not supported by LWF(S)
(would be interesting to know if there is any technical reason
for that. Some limitation maybe).
Is there any way of doing text shadows and stroke not using
filters?

**Comment by splhack** [comment]
You can set text properties via **Link** option on Flash text property panel. But these properties might not be supported by the runtime.

- vertical alignment
  - `valign=top`
  - `valign=middle`
  - `valign=bottom`
- stroke
  - `strokeWidth=(number)`
    - e.g. `strokeWidth=16`
  - `strokeColor=(color code)`
    - e.g. `strokeColor=000000`
- shadow
  - `shadowColor=(color code)`
    - e.g. `strokeColor=000000`
  - `shadowOffsetX=(number)`
    - e.g. `shadowOffsetX=4`
  - `shadowOffsetY=(number)`
    - e.g. `shadowOffsetY=4`
  - `shadowBlur=(number)`
    - e.g. `shadowBlur=2`

Examples:

    valign=middle,strokeWidth=4,strokeColor=ff0000

    shadowColor=000000,shadowOffsetX=2,shadowOffsetY=2,shadowBlur=2


![text_property](https://cloud.githubusercontent.com/assets/81904/5841960/fb09fc94-a155-11e4-9886-c74c583e58e2.png)
