### ISSUE TITLE
Can't link lua bindings in Cocos Code IDE

### ISSUE THREAD

**Issue by Edeleiz** [gree/lwf#107]
No tutorials were found, please can you help with using awesome lwf library in Cocos Code IDE lua project?

**Comment by splhack** [comment]
Unfortunately, right now, LWF doesn't have some Lua bindings for Cocos2d-x Lua project. You can use Lua for controlling LWF itself, but in the meantime, you need to write C++ code to instantiate LWFObject to the scene. We need to consider how to support Cocos2d-x Lua project.

**Comment by splhack** [comment]
Same as #71
