### ISSUE TITLE
[Cocos2dx] Lwf library Visual Studio 2013 support (Win32)

### ISSUE THREAD

**Issue by masfed** [gree/lwf#108]
Hi All. I am newbie in Cocos2dx and Lwf. I develop crossplatform game on Cocos2dx. I have already run sample Cocos2dx application on most platforms including Win32. Then I have found LWF library and successfully include it to iOs and Android project. Also I tried to include it in Visual Studio 2013 Cocos2dx project, but I have get a lot of issues with linking and compiling with visual studio compiler.
I have spend two days on them and still i have to much issues.
It seemed that LWF does not support Win32 applications at all. Maybe I do something wrong.
Could you please provide Visual Studio 2013 Win32 Cocos2dx3.3 with LWF sample application (https://github.com/splhack/Hello-LWF-Cocos2d-x/).
Maybe some other members of GitHub may provide it. I will be very grateful for help.
Sorry for my poor English.

**Comment by splhack** [comment]
Could you try the latest https://github.com/splhack/Hello-LWF-Cocos2d-x ?

Many thanks to @stari4ek for contributing Visual Studio 2013 project and patches.
- https://github.com/gree/lwf/pull/109
- https://github.com/splhack/Hello-LWF-Cocos2d-x/pull/2

**Comment by masfed** [comment]
Thanks for reply.
