### ISSUE TITLE
LWF background can't be transparent

### ISSUE THREAD

**Issue by zafyraminx** [gree/lwf#110]
Hello I am using LWF in my project but the problem is it can't be transparent is there any way to make it transparent? and the color of the image is change.

![screenshot from 2015-02-04 10 17 11](https://cloud.githubusercontent.com/assets/10840583/6034614/cde698c0-ac5f-11e4-8094-7c22d4fbca77.png)

**Comment by splhack** [comment]
Sorry, LWF for Pure2D has been no longer supported. I recommend you to use LWF for Cocos2d-x on Android.
