### ISSUE TITLE
texture export premultiply alpha  

### ISSUE THREAD

**Issue by quicklyslow** [gree/lwf#120]
First of all, thanks for the great lwf, saving a lot of work for me. There is a problem not solved for a while;

The swf files I created with alpha channel, the exported pngs looks different when using command in flashcs "Publish for LWF" and LWFS(or swf2lwf.rb), it seems that LWFS had alpha premultiplied but I am not so sure, if it is, may there be any way to disable the premultiply?
![t1_texture](https://cloud.githubusercontent.com/assets/2765775/6977731/84c0127e-d9f6-11e4-92db-b663a09b6518.png) the image generate by LWFS
![t1_texture](https://cloud.githubusercontent.com/assets/2765775/6978250/dd5823ae-da00-11e4-8a05-f6e85ea28ae1.png)
the image generate in flashcs with command "Publish for LWF"<---this what I actually need.

**Comment by splhack** [comment]
glad to hear that!

"Publish for LWF" command extracts bitmaps as is from fla file. And LWFS copies automatically the extracted bitmaps in LWFS_work folder to LWFS_work_output folder. The issue sounds that you have only swf file in LWFS_work folder. Could you check your LWFS_work folder?


For example

    LWFS_work/
              effectA/
                      effectA.bitmap/
                                     effect1.png
                                     effect2.png
                      effectA.fla
                      effectA.swf

**Comment by quicklyslow** [comment]
I put both of my effect.swf and effect.fla into LWFS_work folder, and using lwfs, but in the LWFS_work_output folder, the pngs in effect.swf folder is different from generated in flashcs, just as the 2 pngs I posted. The same effect.swf and effect.fla file.
I want to use swf2lwf.rb so I can deal all this by a .sh script, but even if I add fla file in the parameter passed to swf2lwf.rb, the pngs generated is still the same as lwfs generated.

**Comment by splhack** [comment]
Did you create a subfolder in LWFS_work folder as I said? For example, "LWFS_work/effect/". And you should put fla file into the subfolder, "LWFS_work/effect/effect.fla". Then execute "Publish for LWF" command.

**Comment by quicklyslow** [comment]
I'm so sorry maybe I did not explain clearly what I need.
I can execute "Publish for LWF" in flashcs and generated by LWFS in subfolder with fla file or swf2lwf.rb -p , but the result is different, in flashcs the exported PNG files are without premultiplied alpha but LWFS and swf2lwf.rb exports premultiplied alpha PNG files.
What I actually need is the PNG files without premultiplied alpha. Is there any way to do this by swf2lwf.rb or LWFS?

**Comment by splhack** [comment]
No. As I said, swf2lwf.rb exports **premultiplied alpha** PNG files from swf if you specify "-p" option (swf does have actually only **premultiplied alpha** images). LWFS itself doesn't have such function. Thus you need to use "Publish for LWF" command to export no-premultiplied-alpha PNG files from fla.

**Comment by quicklyslow** [comment]
Thank you for your explanation, I understand eventually. swf file itself only have premultiplied alpha PNG files.
Then I should only use "Publish for LWF" command and I can not batch this operation.
