### ISSUE TITLE
lwf can't load in android phone that is not rooted

### ISSUE THREAD

**Issue by zafyraminx** [gree/lwf#123]
the lwf loadlibrary having a problem loading th libs when i am using not rooted phone but in some phone it is fine. i mean if i use rooted phone who has access in other lib folder. i think the problem is in the liblwf-pure2d.so because i try to call it in the data/data/packname/libs but it can't call the libgnustl_shared.so file so i think there is something wrong in it. but i can't edit it so tell me is there any fix about it??

I think there is something that need to change in needed .so, I hope you can help me with this.

**Comment by splhack** [comment]
Sorry, LWF for Pure2D is no longer supported. I recommend you to use LWF for Cocos2d-x on Android.

**Comment by zafyraminx** [comment]
Ohh I see but the problem is I don't use Cocos2d-x because i use java for android. but maybe i will try it. but you dont have other .so file that can give me?

**Comment by splhack** [comment]
You can build it yourself. https://developer.android.com/tools/sdk/ndk/index.html

**Comment by zafyraminx** [comment]
okey thanks. i will try.
