### ISSUE TITLE
Texture replacing in Javascript

### ISSUE THREAD

**Issue by chargo** [gree/lwf#128]
Hi,
Is it possible to replace textures in Javascript? I've only found examples of Unity or Cocos-2d, like https://github.com/gree/lwf/issues/19 , but not in Javascripts/html5. Tried to assign value to lwf.data.textures[index], but nothing happened. Thanks!

**Comment by splhack** [comment]
Yes it is, at loading time. You can specify `imageMap` object or function in `loadLWF` parameter to replace the url of images.

https://github.com/gree/lwf/blob/master/coffee/webkitcss/lwf_webkitcss_resourcecache.coffee#L44-L51

**Comment by chargo** [comment]
Thank you for the fast reply. Besides, what if I want to replace some textures at runtime, like replace the score number sprites? Thanks in advance!

**Comment by splhack** [comment]
> replace the score number sprites

For this case, have a movieclip symbol what has 10 key frames. Each key frame has a number bitmap and a frame label. "0" label has "0" bitmap, "1" label has "1" bitmap, ... It is a common way in Adobe Flash.
