### ISSUE TITLE
Buttons in Unity‏

### ISSUE THREAD

**Issue by DelSystem32** [gree/lwf#137]
In my FLA project I create a button and add a "on (press)" script to it. All the script is supposed to be doing is stop the flash from playing. But in Unity the button doesn't even seem to appear.

I've tried what's suggested here: https://github.com/gree/lwf/issues/27

It doesn't work. I've also downloaded "menu.fla" from: https://github.com/gree/lwf-demo/tree/master/flash

It doesn't work. I've tried to study how it does things but it seems like its methods simply no longer works? Since all these examples and posts I find are 2-3 years old I guess LWF does things differently now.

How should I set up buttons in my FLA project and how can I catch the events in Unity's C# scripts? (press/release/rollOver/rollOut etc)

**Comment by splhack** [comment]
- Install LWFS https://github.com/gree/lwfs
 - Launch LWFS
 - Create a folder in "LWFS_work" folder and put your fla file into the folder.
 - Execute "Publish for LWF" from your data in the command menu of Adobe Flash CS6 or CC 2015. The command "Publish for LWF" is automatically installed by LWFS.
 - LWFS automatically converts fla and swf data into lwf data.
 - Get lwf data and texture files from "LWFS_work_output/unity/your_folder" folder.

**Comment by DelSystem32** [comment]
That didn't relate to my question at all, I'm wondering how to get buttons to work.

I can put the flash into Unity. But any buttons does not work, I would like a small guide (example) on how to get a working button in Unity.

Just something that when pressed executes Debug.Log("Hello!"); in unity's C# script would be enough for me to understand.

1) How should the button be set up in the FLA project?
2) How do I catch the press event in Unity using C#?

**Comment by splhack** [comment]
It's important. Did you follow the instruction?

**Comment by DelSystem32** [comment]
I can't use Publish for LWF because I'm writing a program called LWFmagic. I need to export the flash normally (by pressing CTRL+Enter) and then the program I'm writing takes care of moving it into the LWFS_work folder and everything else.

What does Publish for LWF do exactly? Is it something that can't be done in some other way?

**Comment by splhack** [comment]
> Is it something that can't be done in some other way?

Please take a look at https://github.com/gree/lwf/blob/master/tools/flash/Publish%20for%20LWF.jsfl

> I thought only .swf files should be placed into "LWFS_work" but does it also need the .fla file?

Why don't you try to follow the instruction?

**Comment by DelSystem32** [comment]
>Why don't you try to follow the instruction?

1) Alrighty, I created "a_folder" inside LWFS_work
2) I placed Test.fla into it and opened it in Flash CS6
3) I used Commands > Publish for LWF
4) a_folder now contains: Test.bitmap (an empty folder), Test.fla, Test.fla~ and Test.swf
5) Inside LWFS_work_output\unity\a_folder there are two files: "Test.bytes" and "Test_0.png"
6) I copy these in my Unity project, refresh the Unity project and press play
7) The LWF appears exactly like it did before (incorrect fonts)

What am I doing wrong? Do I need to edit swf2lwf.conf in notepad first?

**Comment by DelSystem32** [comment]
Here is what I just tried:

In butt.fla (blank Flash project) I created a new symbol of type MovieClip, made a square, set it to "export as bitmap". This will be the flash background and its instance name is "buttbg".

I made a new layer. On it I place a new symbol of type Button. It has one keyframe with a square of 50% alpha color #66ffff in it (the keyframe spans over all four frames of the button (up/over/down/hit). The button's instance name is "mybutt" and it covers the background MovieClip.

On the button instance I place this code:

    on (press) {
        fscommand("event", "mybuttpress");
    }

I then used Command > Publish for LWF, which gave me the following message:

    WARNING: #66ffff7f
    WARNING: Corrected LinkageName: button: "Symbol 2" -> "button0"
    WARNING: Corrected LinkageName: movie clip: "Symbol 1" -> "movie0"

After it finished I copy the following files to the LWFS_work folder: "Butt.bitmap" (empty folder), "Butt.fla", "Butt.fla~" and "Butt.swf"

In the "LWFS_work_output\unity\Butt.swf" folder I copy two files into Unity: "Butt.bytes" and "Butt_0.png"

On the LWFObject that Load() the flash I place the following script:

    SetButtonEventHandler("mybuttpress", press:(b) => {
            Debug.Log("Click 1!");
        });
    SetButtonEventHandler("mybutt", press:(b) => {
            Debug.Log("Click 2!");
        });

I now play the game in Unity. The button background ("buttbg") appears but it doesn't react when I click it ("Click 1!" or "Click 2!" is not printed to the console).

When the LWFObject loads the flash I specify that the UI camera (that renders the flash in mode) should be used as "inputCamera". I don't really understand what inputCamera or renderCamera do yet but I can figure that out once I get buttons to work.

What am I doing wrong?

**Comment by splhack** [comment]
Have you tried https://github.com/splhack/Hello-LWF-Unity ? The cats plays jump animation when you click the cats, right? If so, you can put your lwf data into the project. And copy SimpleLWF.cs to a new cs file, modify to load your lwf data, and, add `SetButtonEventHandler` snippet.

**Comment by DelSystem32** [comment]
That doesn't answer the "what am I doing wrong" question though, I spent time writing that detailed post in hopes of being informed about what I actually did wrong.

I haven't tried that Hello World example, but I could. Do I have to use Lua? I don't want to have to use anything except C# (even Lua inside C#). Is the FLA project file available? I don't see it, being able to set up buttons correctly in the flash is very important.

**Comment by splhack** [comment]
You don't have to use Lua and the FLA file doesn't exist but it doesn't matter. The project just ensure touch event actually works with LWF on Unity. And you can test your data on the project. It means touch event should work as well. That's it.

**Comment by DelSystem32** [comment]
So you're saying that buttons are no longer supported and that only MovieClips should be used in the FLA project file now? And that all LWF.Movie objects in Unity will receive press events and so forth?

**Comment by splhack** [comment]
Sorry, I don't get why you got the assumption. There are a lot of possibility why button doesn't work. But, at least, in the project https://github.com/splhack/Hello-LWF-Unity , buttons works pretty fine. Thus I recommend you to try the project first. And then you can test your data in the project. It would isolate the issue, it could be LWF data problem, or Unity scene(camera) problem. The project uses a bit old LWF code, but it doesn't matter. You can override with the latest code. By the way, have you reed https://github.com/gree/lwf/issues/61?

**Comment by DelSystem32** [comment]
I hadn't seen that, I'll try to get buttons working tomorrow (starting with "Hello-LWF-Unity"). If I can only get those working I'm ready to release another version of LWFmagic. Thanks for all the help so far!

By the way, concerning my "assumption": Did you mean that only buttons can receive events such as press/release or did you mean that both buttons and movieclips can receive these events?

**Comment by splhack** [comment]
Only buttons can receive press/release/rollOver/rollOut events, though movieclips has general event system (AddEventHandler/SetEventHandler, DispatchEvent).

**Comment by DelSystem32** [comment]
Hello-LWF-Unity is doing nothing for me, is there really nothing else? Maybe something that at least provides a FLA project?

**Comment by splhack** [comment]
Have you open Main scene?

**Comment by DelSystem32** [comment]
Yeah it's loading the following into Lua:

    LWF.Script.cat.chara_0_buttonSymbol_x0_y_30_press = function(self)
        self:gotoAndPlay("jump")
    end

If you can help me get it to work without Lua it would be great. I'm assuming I can replace the following lines in cat.cs:

    L = new Lua();
    L.DoString(script.text);
    Load("cat/cat", luaState:L.luaState);

With something like:

    Load ("cat/cat");
    lwf.SearchButtonInstance(?);

Though I don't really know what to put in there since the example is lacking the fla project.

In my own example I seem to be able to find the button instance lwf.SearchButtonInstance so maybe the FLA project I'm using has the button set up correctly, however it doesn't react when I click the button (no events seem to be fired by LWF).

**Comment by splhack** [comment]
um, that's not following what I said.

> The cats plays jump animation when you click the cats, right? If so, you can put your lwf data into the project. And copy SimpleLWF.cs to a new cs file, modify to load your lwf data, and, add SetButtonEventHandler snippet

> Thus I recommend you to try the project first. And then you can test your data in the project. It would isolate the issue, it could be LWF data problem, or Unity scene(camera) problem.

1. The cats plays jump animation when you click the cats, right?
2. put your lwf data into the project
3. copy SimpleLWF.cs to a new cs file
4. modify to load your lwf data
5. add SetButtonEventHandler

**Comment by DelSystem32** [comment]
I modified my FLA project and added a short animation at frame label "jump". Frame 1 I label as "first". In the frame before "jump" I put the script gotoAndPlay("first"); so that the "jump" frame is not reached by default.

I convert it to LWF format and put it into the Unity project.

In cat.cs I replace
    Load("cat/cat", luaState:L.luaState);
with
    Load("ButtSwf/Butt", luaState:L.luaState);

Now it should be just like the cat right? When I click the thing it should gotoAndPlay("jump") in my thing.

I play and the thing appears just like in Unity. It goes back to "first" when it should, "jump" is not reached by default. However, nothing happens when I click the thing, it does not go to the frame labelled "jump".

**Comment by splhack** [comment]
that's not following what I said...

1. The cats plays jump animation when you click the cats, right?

Could you check it? It worked?

1. put your lwf data into the project
2. copy SimpleLWF.cs to a new cs file, create a GameObject and attach the cs file
3. modify the cs file to load your lwf data
4. add SetButtonEventHandler

**Comment by DelSystem32** [comment]
I've finally been able catch the event in C#. Thank you! Seems like there are three issues now:

1) The hitbox of the button is incorrect in Unity - the button corners is not the same as in flash. [major issue]
2) Commands > Publish for LWF breaks the script placed on the button itself in the FLA project. [minor issue for me]
3) Objects placed in front of the button in Unity does not prevent the button from being pressed. [could be worked around but is inconvenient]

Are there solutions to these things? Especially the 1st issue is a big concern.

**Comment by splhack** [comment]
1) It's the same. see #61 
2) I don't understand
3) You can override LWFObject.Update whatever you want https://github.com/gree/lwf/blob/a6451b223bd5683e0bb2c732a9efe0c51dbb4944/csharp/unity/wrapper/LWFObject.cs#L374-L387

**Comment by DelSystem32** [comment]
1) Nope, not for me. Strange huh? I click outside the button area in Unity and the button gets pressed. Can't find anything about this issue in #61.
2) If you have something like on (press) {gotoAndPlay("jump");} on your button in the FLA it will work in Unity if you Ctrl+Enter to create the flash but not if you use "Publish for LWF" (Publish for LWF.jsfl makes the button's script not execute when you click the button in Unity).
3) Okay so nothing is built-in for that. It looks like that code in Update is confirming what I was guessing "inputCamera" does, however it just makes it weirder that it doesn't actually work. I'm starting to wonder if I should write my own raycast logic for dealing with mouse events since figuring out what is wrong with the built-in stuff is taking such a long time.
