### ISSUE TITLE
Depth in Unity

### ISSUE THREAD

**Issue by DelSystem32** [gree/lwf#138]
When a flash is loaded into Unity by LWFObject.Load the different MovieClips are get different Z values depending on their layer and sorting order in the flash. However how can I get (and change) their depth afterwards?

lwf.rootMovie.depth always returns a depth of 0.
lwf.SearchMovieInstance("ExampleInstanceName").depth always also returns a depth of 0.

Setting these values to (for example) 1/-1 doesn't seem to change anything, the Z values stays the same and nothing changes in the way they are rendered.

How do I get and change the depth of a MovieClip (LWF.Movie) in Unity?

**Comment by splhack** [comment]
`Movie.depth` is for internal use, and LWF doesn't expose the depth of Movie. So you need to modify the code for it.

**Comment by DelSystem32** [comment]
Okay, just to verify: It's impossible to swap the render order of two MovieClips in LWF? I have to find some kind of workaround myself?

**Comment by splhack** [comment]
You may be able to use `Movie.AttachMovie` and `Movie.SwapAttachedMovieDepth` APIs to swap the order. You can attach a movie with the LinkageName of MovieClip into the other movie.

**Comment by DelSystem32** [comment]
I can't figure out how. After I use Load() on a LWFObject surely all LWF.Movie instances becomes attached already?

For the sake of trying I tried this in the LWFObject after it has called Load:

    AttachMovie("thebox1", "thebox1", "thebox1", 0);
    AttachMovie("thebox2", "thebox2", "thebox2", 1);
    SwapAttachedMovieDepth("thebox2", 1, 0);

thebox1 and thebox2 are two MovieClip instances in the original flash. So here I'm guessing I'm assigning them the depth of 0 and 1? Then I try to swap these depths - at least from the looks of it that is what SwapAttachedMovieDepth would do; rearrange the "thebox2" instance. But nothing happens. I've tried SwapAttachedMovieDepth("thebox2", 0, 1); as well but that does nothing.

Not sure why I would have to assign depths to the movieclips myself after using Load in the first place, since they already have different Z these depth values should be assigned automatically during Load.

**Comment by splhack** [comment]
LWF doesn't have the functionality, swapping depth in the timeline that was created on Adobe Flash. But you can attach a movie onto the other movie dynamically.

Please take a look at https://github.com/gree/lwf/issues/88#issuecomment-57821200, https://github.com/gree/lwf/issues/51.

**Comment by DelSystem32** [comment]
That's an unfortunate limitation. Good to know, thank you! Being able to change the Z value of a LWF.Movie would be a nice future feature.
