### ISSUE TITLE
Dimensions in Unity

### ISSUE THREAD

**Issue by DelSystem32** [gree/lwf#139]
How can I get the width/height of a MovieClip (LWF.Movie) that has been loaded into Unity?

Something like this would be great for example:
lwf.SearchMovieInstance("ExampleInstanceName").width

But that doesn't exist. Right now all I can do is get all of the Renderers of the GameObject that LWFObject is attached to and calculate the width using all of their bounding boxes, this isn't very good however since it becomes affected by things like GameObject scale/rotation.

I know I can get the stage size of the flash from "lwf.width" and "lwf.height" but that isn't good enough, I'd like to be able to get the width/height of the movieclips inside the flash as well.

**Comment by splhack** [comment]
Use Movie.RequestCalculateBounds or LWFObject.RequestCalculateBoundsMovie.

    movie.RequestCalculateBounds((m) => {
        LWF.Bounds b = m.GetBounds();
        Debug.Log(string.Format("{0} {1} {2} {3}", b.xMin, b.xMax, b.yMin, b.yMax));
    });

**Comment by DelSystem32** [comment]
Thanks for trying to help. It looked promising but unfortunately it didn't work. I tried the following inside a LWFObject:

    void FixedUpdate() {
    	string mcInstanceName = "topbar";
    	LWF.Movie m = lwf.rootMovie;
    	if (mcInstanceName!=null) {
    		m = lwf.SearchMovieInstance(mcInstanceName);
    	}
    	m.RequestCalculateBounds((mov)=> {
    		Debug.Log("test1");
    	});
    	RequestCalculateBoundsMovie(mcInstanceName, (mov)=> {
    		Debug.Log("test2");
    	});
    	Debug.Log(lwf.rootMovie.GetBounds());
    	Debug.Log(lwf.SearchMovieInstance(mcInstanceName).GetBounds());
    }

The output every time it was executed was alway Null from the two GetBounds() calls and "test1"/"test2" was never printed, meaning that none of the callbacks were ever called.

**Comment by splhack** [comment]
I recommend you to use Unity debugger to track why the callback was never called. Anyway `GetBounds()` doesn't work in your code snippet, it should be in the callback.

**Comment by DelSystem32** [comment]
I don't intend to correct any of LWF's code though, I don't have the time, but it's good for the developer(s) of LWF to know that something is broken with RequestCalculateBounds. It would be nice with a method that returns the bounds immediately (no "request" required), I'm assuming it would take at least a frame before that calculate callback arrived which isn't too useful.

**Comment by splhack** [comment]
Ok, I've found and fixed the problem db15f61d7daa18781e18989ec3df63ddf3472fea .

**Comment by DelSystem32** [comment]
Great job dude, everything's working! Thanks!
