### ISSUE TITLE
Non-movable buttons

### ISSUE THREAD

**Issue by DelSystem32** [gree/lwf#142]
LWF.Movie has a Move(x,y) and MoveTo(x,y) method. LWF.Button does not.

Is there any way to move buttons or can only MovieClips be moved in LWF?

**Comment by DelSystem32** [comment]
Also, are text fields moveable?

**Comment by splhack** [comment]
LWF.Movie only has Move and MoveTo API.

**Comment by DelSystem32** [comment]
After further testing it seems like buttons inside MovieClips do not move even if I move the LWF.Movie that contains the button, is this correct?

Buttons can not be moved no matter what?

**Comment by splhack** [comment]
LWF.Movie object and the contents in the LWF.Movie object should be updated after LWF.Exec API executed.

**Comment by DelSystem32** [comment]
Okay seems like I can movie buttons by moving their container MovieClip after all. But things are getting strange with the bounds, probably going to have to open up a new issue.
