### ISSUE TITLE
gem install gems/rb-img*.gem,   I got the following err:

### ISSUE THREAD

**Issue by irene-coming** [gree/lwf#65]
$ gem install gems/rb-img*.gem
Building native extensions.  This could take a while...
ERROR:  Error installing gems/rb-img-0.0.7.gem:
    ERROR: Failed to build gem native extension.

```
/Users/pm-minit/.rvm/rubies/ruby-2.0.0-p353/bin/ruby extconf.rb
```

checking for zlib.h... yes
checking for png.h... no
checking for jpeglib.h... no
checking for main() in -lz... yes
checking for main() in -lpng... no
checking for main() in -ljpeg... no
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling img.c
img.c:10:10: fatal error: 'png.h' file not found
# include <png.h>

```
     ^
```

1 error generated.
make: **\* [img.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/pm-minit/.rvm/gems/ruby-2.0.0-p353/gems/rb-img-0.0.7 for inspection.
Results logged to /Users/pm-minit/.rvm/gems/ruby-2.0.0-p353/extensions/x86_64-darwin-12/2.0.0-static/rb-img-0.0.7/gem_make.out

I'm using mac os x 10.9.2

**Comment by zenubis** [comment]
@AlmirKadric Thanks for the solution. It works nicely. Although in my case my png.h was in /usr/local/include instead.

**Comment by AlmirKadric** [comment]
@zenubis :+1: glad it helped

**Comment by sylistine** [comment]
This sort of helps, but I'm neither on a mac or linux computer. I downloaded libpng and used `C_INCLUDE_PATH=/c/path/to/libpng` in git bash while running `gem install gems/rb-img*.gem` but got a fancy new error `fatal error: pnglibconf.h: No such file or directory compilation terminated.`

Is this not the libpng I should be using? http://www.libpng.org/pub/png/libpng.html

**Comment by sylistine** [comment]
For windows users: if you don't have `pnglibconf.h`, opening up png.h and going to the error line shows you ```
    /* If pnglibconf.h is missing, you can
     * copy scripts/pnglibconf.h.prebuilt to pnglibconf.h
     */```

So if you cp `scripts/pnglibconf.h.prebuilt` to `pnglibconf.h` you'll  clear that one hurdle, HOWEVER!

New problem: `jpeglib.h: No such file or directory`
So I guess just rinse and repeat till your problem is solved.

**Comment by KojiNakamaru** [comment]
Yes, on windows preparing ruby with required gems is complicated. I utilizes https://github.com/gree/lwfs/blob/12d0ad5489b52208a9b1eae2bcf474cae1056115/build/win/runtime/Makefile on cygwin to prepare such a ruby (note: resulting ruby and installed gems won't require cygwin).

If you want to run swf2lwf.rb as is on windows, please try to utilize LWFS as noted in https://github.com/gree/lwf/issues/65#issuecomment-43788863 . An LWFS release (https://github.com/gree/lwfs/releases) contains ruby with required gems. Of course utilizing LWFS as is should be okay if you don't need your custom conversion pipeline.
