### ISSUE TITLE
LWF loads on scene during game preview but fails to load on game itself.

### ISSUE THREAD

**Issue by grooovylim** [gree/lwf#89]
Hi,

I've been trying to get my swf (lwf) to load on game play but to no avail.

Here is what I see in the game preview, the animation doesn't load:
![image](https://cloud.githubusercontent.com/assets/6916002/4503017/d03bc98c-4ad1-11e4-851e-f2dfc09c9727.png)

But on the scene preview, the file loads fine:
![image](https://cloud.githubusercontent.com/assets/6916002/4503027/ec954414-4ad1-11e4-81dc-02a52c1566b4.png)

May I know how should I go about troubleshooting this?

**Comment by splhack** [comment]
Could you try the latest code? LWFObject now has UseUIVertexRenderer() API for selecting a renderer that works well on/with uGUI.
